### ISSUE TITLE
Hifiasm for scaffolding

### ISSUE THREAD

**Issue by LHG-GG** [ShunOuchi/GreenHill#17]
@ShunOuchi 

Hi, 

I have phased assembly from hifiasm in trio mode. If I want to use GreenHill only for chromosome level scaffolding, how do I do that? 

If I understand correctly, GreenHill should also work for Omni-C data? Any plans on implements PoreC reads directly? 

Thank you

**Comment by ShunOuchi** [comment]
Hi,

If you want to use GreenHill for scaffolding without phasing, only use -c option.
In this case, use out.ConsensusOutput.fa as the final result.
`greenhill -c hifiasm.dip.hap1.p_ctg.fa -p HiFi.fq -HIC HIC_1.fq HIC_2.fq`
`greenhill -c hifiasm.dip.hap2.p_ctg.fa -p HiFi.fq -HIC HIC_1.fq HIC_2.fq`
Note that it may not be possible to create the genome correctly unless the input reads are separated into maternal and paternal haplotypes.

GreenHill also work with Omni-C data because it does not use restriction enzyme information. As of now, I don't have plans on implements PoreC reads directly.  Sorry.

**Comment by LHG-GG** [comment]
hi @ShunOuchi,
Thank you.

1) As I am interested in HiC based scaffolding, is it necessary to provide long reads (`-p`)? If yes, for trio based assembly, do I have to bin the `-p` reads as well as HiC reads like you have mentioned above? 

2) I binned the HiC reads and ran Greenhill like above, the job ran for 2 days and got killed due to time limit of HPC (attached the log).  What is the expected time for 60x of `-p` and 60x of `-HIC` reads. 
[greenhill_triomode_log.txt](https://github.com/ShunOuchi/GreenHill/files/12574458/greenhill_triomode_log.txt)

**Comment by ShunOuchi** [comment]
> As I am interested in HiC based scaffolding, is it necessary to provide long reads (-p)? If yes, for trio based assembly, do I have to bin the -p reads as well as HiC reads like you have mentioned above?

It is not necessary to provide long reads for Hi-C scaffolding, but GreenHill also has the scaffolding function with long reads, so providing long reads may increate continuity.

> I binned the HiC reads and ran Greenhill like above, the job ran for 2 days and got killed due to time limit of HPC (attached the log). What is the expected time for 60x of -p and 60x of -HIC reads.

In my environment, it took about 8 hours with zebra finch sample (1 Gb genome, 39Gb of HiFi reads and 95 Gb of Hi-C reads), -t 48. See table S4 in the [paper](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-023-03006-8) for details.

However, some samples may take longer and may take more than 2 weeks. I think this is due to slow update of link information when contigs are cut, but we have not been able to improve this. We would like to improve it and update in the future.

 If you run GreenHill without long read(-p), you may be able to run it a little faster.

Thank you
