### ISSUE TITLE
the number of read is odd in file 

### ISSUE THREAD

**Issue by huangl07** [ShunOuchi/GreenHill#27]
![image](https://github.com/ShunOuchi/GreenHill/assets/32302403/059c7244-b50c-420b-bf16-6167a4c5ead0)

hello，My dear，how to fix it？ thankyou！

**Comment by ShunOuchi** [comment]
Sorry for the late reply.

I can't see the input data or logs, so I don't know exactly, but perhaps this error is due to the different number of reads in Paired-End or Hi-C file. The number of the reads in R1.fastq must be equal to the number of reads in R2.fastq.
Please check the number of reads in Paired-End and Hi-C file using a tool such as [seqkit](https://github.com/shenwei356/seqkit).

Thank you
